@client_service_HostAddress = https://localhost:5000

###
POST {{client_service_HostAddress}}/users/login
Content-Type: application/json

{
  "email": "earnestine_wuckert@oga.us",
  "password": "g[4h\"rK](U"
}

###
GET {{client_service_HostAddress}}/work/678bdabaf1fc1b68ef000000

###
POST {{client_service_HostAddress}}/work
Content-Type: application/json

{
  "name":"My First Work",
  "type": "Type flag",
  "reference": "External Reference"
}

###
POST {{client_service_HostAddress}}/work
Content-Type: application/json

{
  "name":"",
  "type": "Type flag",
  "reference": "External Reference"
}


###
PATCH {{client_service_HostAddress}}/work
Content-Type: application/json

{
  "updatedProperties": [
    { "Name" :  "Name", "Value":  "" },
    { "Name" :  "Reference", "Value":  "1234567890 1234567890 1234567890 1234567890 "}
    ]
}

###
DELETE {{client_service_HostAddress}}/work/123

###
POST {{client_service_HostAddress}}/users/workTypes
Content-Type: application/json

{
  "workType": "New work 2025-02-25:01"
}
